### ISSUE TITLE
Which version of pytorch did you use?

### ISSUE THREAD

**Issue by philipperemy** [Lingkai-Kong/SDE-Net#6]
I get this error with pytorch 1.7

```
Epoch: 0
Traceback (most recent call last):
  File "sdenet_mnist.py", line 139, in <module>
    train(epoch)
  File "sdenet_mnist.py", line 99, in train
    label = torch.full((args.batch_size,1), real_label, device=device)
RuntimeError: Providing a bool or integral fill value without setting the optional `dtype` or `out` arguments is currently unsupported. In PyTorch 1.7, when `dtype` and `out` are not set a bool fill value will return a tensor of torch.bool dtype, and an integral fill value will return a tensor of torch.long dtype.
```

**Comment by philipperemy** [comment]
So seems like it works with `pytorch==1.5.1 torchvision==0.6.1` but just wanted to be sure.
